python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/boxes_6dof/images --dst_datapath /media/runqiu/data/davis240c/train/boxes_6dof/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/boxes_translation/images --dst_datapath /media/runqiu/data/davis240c/train/boxes_translation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/dynamic_rotation/images --dst_datapath /media/runqiu/data/davis240c/train/dynamic_rotation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/dynamic_translation/images --dst_datapath /media/runqiu/data/davis240c/train/dynamic_translation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/hdr_poster/images --dst_datapath /media/runqiu/data/davis240c/train/hdr_poster/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1

python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/outdoors_running/images --dst_datapath /media/runqiu/data/davis240c/train/outdoors_running/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/poster_6dof/images --dst_datapath /media/runqiu/data/davis240c/train/poster_6dof/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/poster_rotation/images --dst_datapath /media/runqiu/data/davis240c/train/poster_rotation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/shapes_rotation/images --dst_datapath /media/runqiu/data/davis240c/train/shapes_rotation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/shapes_translation/images --dst_datapath /media/runqiu/data/davis240c/train/shapes_translation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/train/urban/images --dst_datapath /media/runqiu/data/davis240c/train/urban/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1



python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/boxes_rotation/images --dst_datapath /media/runqiu/data/davis240c/valid/boxes_rotation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/calibration/images --dst_datapath /media/runqiu/data/davis240c/valid/calibration/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/dynamic_6dof/images --dst_datapath /media/runqiu/data/davis240c/valid/dynamic_6dof/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/hdr_boxes/images --dst_datapath /media/runqiu/data/davis240c/valid/hdr_boxes/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/outdoors_walking/images --dst_datapath /media/runqiu/data/davis240c/valid/outdoors_walking/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/poster_translation/images --dst_datapath /media/runqiu/data/davis240c/valid/poster_translation/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
python3 interpolate.py configs/config_rpgevent.py --src_datapath /media/runqiu/data/davis240c/valid/shapes_6dof/images --dst_datapath /media/runqiu/data/davis240c/valid/shapes_6dof/images_4x --src_file_stye frame_%08d.png --dst_file_stye %06d.png --numbias 1
